export const warehouses = [
  {
    id: 1,
    name: 'Bodega 1',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 1',
    status: true,
  },
  {
    id: 2,
    name: 'Bodega 2',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 2',
    status: false,
  },
  {
    id: 3,
    name: 'Bodega 3',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 3',
    status: true,
  },
  {
    id: 4,
    name: 'Bodega 4',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 4',
    status: true,
  },
  {
    id: 5,
    name: 'Bodega 5',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 5',
    status: false,
  },
  {
    id: 6,
    name: 'Bodega 6',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 6',
    status: true,
  },
  {
    id: 7,
    name: 'Bodega 7',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 7',
    status: false,
  },
  {
    id: 8,
    name: 'Bodega 8',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 8',
    status: true,
  },
  {
    id: 9,
    name: 'Bodega 9',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 9',
    status: true,
  },
  {
    id: 10,
    name: 'Bodega 10',
    location: 'Merida',
    register: '23-10-2025',
    owner: 'Propietario 10',
    status: false,
  },
];
